### ISSUE TITLE
joelametta/whipper does not exist

### ISSUE THREAD

**Issue by jrlepage** [thomas-mc-work/most-possible-unattended-rip#10]
Getting this error: pull access denied for joelametta/whipper, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

And can’t find joelametta/whipper on Docker Hub... is there a workaround?

**Comment by jrlepage** [comment]
I tried substituting whipperteam/whipper in the Dockerfile and get this:

```
Step 1/10 : FROM whipperteam/whipper

 ---> 0ea7d4a5a5eb
Step 2/10 : ENV LOG_DIR=/logs

 ---> Running in bb82b2ababf8
Removing intermediate container bb82b2ababf8
 ---> 34b1210998a0
Step 3/10 : USER root

 ---> Running in 064f16a23154
Removing intermediate container 064f16a23154
 ---> 99b3286f8f39
Step 4/10 : RUN pip install --quiet beets munkres==1.0.12   && apt-get install -yqq python-requests   && mkdir /home/worker/.config/beets && chown worker: /home/worker/.config/beets   && mkdir -p -- "$LOG_DIR"   && chown worker: "$LOG_DIR"

 ---> Running in 7f64c3dfb19e
/bin/sh: 1: pip: not found
The command '/bin/sh -c pip install --quiet beets munkres==1.0.12   && apt-get install -yqq python-requests   && mkdir /home/worker/.config/beets && chown worker: /home/worker/.config/beets   && mkdir -p -- "$LOG_DIR"   && chown worker: "$LOG_DIR"' returned a non-zero code: 127
```

**Comment by jrlepage** [comment]
Sorry for the running commentary here, but I changed “pip” to “pip3” in the Dockerfile and now I’m getting this:

‘Step 1/10 : FROM whipperteam/whipper

 ---> 0ea7d4a5a5eb
Step 2/10 : ENV LOG_DIR=/logs

 ---> Using cache
 ---> 34b1210998a0
Step 3/10 : USER root

 ---> Using cache
 ---> 99b3286f8f39
Step 4/10 : RUN pip3 install --quiet beets munkres==1.0.12   && apt-get install -yqq python-requests   && mkdir /home/worker/.config/beets && chown worker: /home/worker/.config/beets   && mkdir -p -- "$LOG_DIR"   && chown worker: "$LOG_DIR"

 ---> Running in 245f01b67920
  Failed building wheel for beets
  Failed building wheel for jellyfish
  Failed building wheel for pyyaml
E: Unable to locate package python-requests
The command '/bin/sh -c pip3 install --quiet beets munkres==1.0.12   && apt-get install -yqq python-requests   && mkdir /home/worker/.config/beets && chown worker: /home/worker/.config/beets   && mkdir -p -- "$LOG_DIR"   && chown worker: "$LOG_DIR"' returned a non-zero code: 100’

**Comment by jrlepage** [comment]
Gah thought I figured it out but no...
troyc/whipper is another image based on Python 2.7 so I changed the “FROM” to that image, but now I get this... I desperately want to get this working.

‘ Step 1/10 : FROM troyc/whipper

 ---> a1ba255be2e3
Step 2/10 : ENV LOG_DIR=/logs

 ---> Running in 7021d2c69db1
Removing intermediate container 7021d2c69db1
 ---> 6fbec69f1308
Step 3/10 : USER root

 ---> Running in 5c2faf2b04f0
Removing intermediate container 5c2faf2b04f0
 ---> d10df5723d5e
Step 4/10 : RUN pip install --quiet beets munkres==1.0.12   && apt-get install -yqq python-requests   && mkdir /home/worker/.config/beets && chown worker: /home/worker/.config/beets   && mkdir -p -- "$LOG_DIR"   && chown worker: "$LOG_DIR"

 ---> Running in 802b433d0e16
Removing intermediate container 802b433d0e16
 ---> 20f3dbe2ca71
Step 5/10 : COPY --chown=worker:worker beets.yml /home/worker/.config/beets/config.cover.yaml

COPY failed: stat /var/snap/docker/common/var-lib-docker/tmp/docker-builder677197633/beets.yml: no such file or directory’

**Comment by jrlepage** [comment]
Got it working... substituting “troyc/whipper” instead of “joelametta/whipper” in the FROM line at the top of the Dockerfile fixed it. FYI the “official” whipper image on Docker hub uses Python3 and the image fails to build miserably using that one...

**Comment by thomas-mc-work** [comment]
Thank you for pointing that out, @jrlepage!

They seem to have changed the reference of the official docker image. And also upgraded to Python 3 in that time. I have to fix my configuration some day.

**Comment by thomas-mc-work** [comment]
I'll leave this issue open until I finished that.

**Comment by jrlepage** [comment]
I'm having a new issue now. I got it installed using the troyc/whipper image, and it analyzed my drive successfully, but when I try to run the mpur.sh script, I get this:

```
tee: /logs/rip-2020-06-26T21-30-38.log: Permission denied
### starting rip process with whipper
tee: /logs/rip-2020-06-26T21-30-38.log: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.3', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/main.py", line 42, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/basecommand.py", line 117, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/basecommand.py", line 117, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/basecommand.py", line 104, in __init__
    self.handle_arguments()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/cd.py", line 301, in handle_arguments
    raise ValueError("Drive offset is unconfigured.\n"
ValueError: Drive offset is unconfigured.
Please install pycdio and run 'whipper offset find' to detect your drive's offset or set it manually in the configuration file. It can also be specified at runtime using the '--offset=value' argument
tee: /logs/rip-2020-06-26T21-30-38.log: Permission denied
### whipper failed with status code 1
```

**Comment by jrlepage** [comment]
I tried a couple of things... first, I added myself to the docker group so I don't have to sudo all my docker commands.
Then I ran whipper offset find using a similar docker command to the drive analyze command you have in the readme.
However, even after finding the offset (mine is 103), it doesn't seem to be working.
Also, the whipper configuration directory in my home folder is empty... I was trying to figure out where I could set the offset manually using the docker image but I couldn't figure it out.
Any help would be appreciated!! Really want to get this working. Thanks :)

```
### starting rip process with whipper
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.3', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/main.py", line 42, in main
    cmd = Whipper(sys.argv[1:], os.path.basename(sys.argv[0]), None)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/basecommand.py", line 117, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/basecommand.py", line 117, in __init__
    self.options
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/basecommand.py", line 104, in __init__
    self.handle_arguments()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.3-py2.7.egg/whipper/command/cd.py", line 301, in handle_arguments
    raise ValueError("Drive offset is unconfigured.\n"
ValueError: Drive offset is unconfigured.
Please install pycdio and run 'whipper offset find' to detect your drive's offset or set it manually in the configuration file. It can also be specified at runtime using the '--offset=value' argument
### result: success (but couldn't find output folder for fetching cover art)

```

**Comment by jrlepage** [comment]
Sorry I seem to keep answering my own questions,... for some reason the $config_dir variable isn't persisting so when I ran the following:

```
docker run --rm \
  --device=/dev/cdrom \
  -v "$config_dir:/home/worker/.config/whipper" \
  troyc/whipper drive analyze

```
It wasn't actually saving a configuration file anywhere,...
Anyway, I changed the above command to:
```
docker run --rm \
  --device=/dev/cdrom \
  -v "$HOME/.config/whipper:/home/worker/.config/whipper" \
  troyc/whipper drive analyze
``` 
And then it actually generated a config file. I then re-ran that command but changed the last bit to "whipper offset find" like this:
```
docker run --rm \
  --device=/dev/cdrom \
  -v "$HOME/.config/whipper:/home/worker/.config/whipper" \
  troyc/whipper offset find
```
And then I was good to go! Sorry for all of the posts!

**Comment by thomas-mc-work** [comment]
Thank you for your courageous investigations! I will come back to your results when updating the project.
